import { RepositoryMetadata } from './rie-types';
export function generateV2Spec(metadata: RepositoryMetadata) {
  const date = new Date(metadata.analyzedAt).toLocaleString();
  const philosophy = metadata.philosophy;
  const roadmap = metadata.roadmap || [];
  const grounding = metadata.validation?.sectionConfidence || {};
  const md = `
# RIE Architectural Specification v2.0
**Project:** ${metadata.name}
**Report Generated:** ${date}
**Core Architecture Score:** ${metadata.validation?.score}%
## 1. Executive Philosophy
${philosophy?.purpose}
### Positioning & Intent
- **Market Positioning:** ${philosophy?.positioning}
- **Architectural Evolution:** ${philosophy?.evolution}
- **Interoperability:** ${philosophy?.interoperability}
### Technical Constraints
${philosophy?.constraints.map(c => `- ${c}`).join('\n')}
## 2. Grounded Architectural Evidence
The following claims have been verified against the deterministic code scan.
| Claim Category | Confidence Score | Status |
|----------------|------------------|--------|
| Overview       | ${grounding['Overview'] || 0}% | ${grounding['Overview'] > 80 ? '✅ VERIFIED' : '⚠️ UNCERTAIN'} |
| Architecture   | ${grounding['Architecture'] || 0}% | ${grounding['Architecture'] > 80 ? '✅ VERIFIED' : '⚠️ UNCERTAIN'} |
| Setup/Setup    | ${grounding['Setup'] || 0}% | ${grounding['Setup'] > 80 ? '✅ VERIFIED' : '⚠️ UNCERTAIN'} |
## 3. Structural Topology
\`\`\`mermaid
graph TD
${metadata.dependencies.slice(0, 10).map(d => `  ${d.source.replace(/[^a-z]/gi, '_')} --> ${d.target.replace(/[^a-z]/gi, '_')}`).join('\n')}
\`\`\`
## 4. Strategic Roadmap
Current and planned evolution of the project architecture.
| Version | Status | Key Features |
|---------|--------|--------------|
${roadmap.map(r => `| ${r.version} | ${r.status.toUpperCase()} | ${r.features.join(', ')} |`).join('\n')}
---
*Generated by ArchLens RIE-Core v2.0_STABLE*
  `.trim();
  const blob = new Blob([md], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `specs-v2.0-${metadata.name.toLowerCase()}.md`;
  a.click();
  URL.revokeObjectURL(url);
}